extends:
  - eslint:recommended
rules:
  accessor-pairs: error # recommended off
  array-callback-return: error # recommended off
  arrow-body-style: error # recommended off
  block-scoped-var: error # recommended off
  class-methods-use-this: error # recommended off
  complexity: error # recommended off
  consistent-return: error # recommended off
  constructor-super: error # recommended off
  curly: # recommended off
    - error
    - all
  default-case: error # recommended off
  dot-notation: error # recommended off
  eqeqeq: # recommended off
    - error
    - smart
  func-style: error # recommended off
  global-require: error # recommended off
  guard-for-in: error # recommended off
  init-declarations: error # recommended off
  lines-between-class-members: # recommended off
    - error
    - always
    -
      exceptAfterSingleLine: true
  max-classes-per-file: error # recommended off
  max-depth: error # recommended off
  max-lines: error # recommended off
  max-lines-per-function: error # recommended off
  max-nested-callbacks: error # recommended off
  max-params: error # recommended off
  max-statements: error # recommended off
  max-statements-per-line: error # recommended off
  multiline-comment-style: # recommended off
    - error
    - separate-lines
  new-cap: error # recommended off
  no-alert: error # recommended off
  no-array-constructor: error # recommended off
  no-await-in-loop: error # recommended off
  no-buffer-constructor: error # recommended off
  no-caller: error # recommended off
  no-class-assign: error # recommended off
  no-console: error # recommended off
  no-const-assign: error # recommended off
  no-constructor-return: error # recommended off
  no-dupe-else-if: error # recommended off
  no-duplicate-imports: error # recommended off
  no-empty-function: error # recommended off
  no-eval: error # recommended off
  no-extend-native: error # recommended off
  no-extra-bind: error # recommended off
  no-extra-label: error # recommended off
  no-floating-decimal: error # recommended off
  no-implicit-globals: error # recommended off
  no-implied-eval: error # recommended off
  no-import-assign: error # recommended off
  no-invalid-this: error # recommended off
  no-iterator: error # recommended off
  no-label-var: error # recommended off
  no-labels: error # recommended off
  no-lone-blocks: error # recommended off
  no-lonely-if: error # recommended off
  no-loop-func: error # recommended off
  no-magic-numbers: error # recommended off
  no-multi-spaces: error # recommended off
  no-multi-str: error # recommended off
  no-negated-condition: error # recommended off
  no-new: error # recommended off
  no-new-func: error # recommended off
  no-new-object: error # recommended off
  no-new-require: error # recommended off
  no-new-symbol: error # recommended off
  no-new-wrappers: error # recommended off
  no-octal-escape: error # recommended off
  no-param-reassign: error # recommended off
  no-path-concat: error # recommended off
  no-process-env: error # recommended off
  no-process-exit: error # recommended off
  no-proto: error # recommended off
  no-return-assign: error # recommended off
  no-return-await: error # recommended off
  no-script-url: error # recommended off
  no-self-compare: error # recommended off
  no-setter-return: error # recommended off
  no-shadow: error # recommended off
  no-sync: error # recommended off
  no-template-curly-in-string: error # recommended off
  no-throw-literal: error # recommended off
  no-undef-init: error # recommended off
  no-undefined: error # recommended off
  no-unmodified-loop-condition: error # recommended off
  no-unneeded-ternary: error # recommended off
  no-unused-expressions: error # recommended off
  no-use-before-define: error # recommended off
  no-useless-call: error # recommended off
  no-useless-computed-key: error # recommended off
  no-useless-concat: error # recommended off
  no-useless-constructor: error # recommended off
  no-useless-escape: error # recommended off
  no-useless-rename: error # recommended off
  no-useless-return: error # recommended off
  no-var: error # recommended off
  no-void: error # recommended off
  object-shorthand: error # recommended off
  padding-line-between-statements: error # recommended off
  prefer-arrow-callback: error # recommended off
  prefer-const: error # recommended off
  prefer-destructuring: error # recommended off
  prefer-exponentiation-operator: error # recommended off
  prefer-named-capture-group: error # recommended off
  prefer-numeric-literals: error # recommended off
  prefer-object-spread: error # recommended off
  prefer-promise-reject-errors: error # recommended off
  prefer-regex-literals: error # recommended off
  prefer-rest-params: error # recommended off
  prefer-spread: error # recommended off
  prefer-template: error # recommended off
  radix: error # recommended off
  require-await: error # recommended off
  require-unicode-regexp: error # recommended off
  semi: # recommended off
    - error
    - always
  sort-imports: error # recommended off
  sort-keys: error # recommended off
  sort-vars: error # recommended off
  spaced-comment: error # recommended off
  strict: error # recommended off
  symbol-description: error # recommended off
  unicode-bom: error # recommended off
  vars-on-top: error # recommended off
  yoda: error # recommended off
