extends:
  - plugin:import/recommended
  - plugin:import/react
  - plugin:import/typescript
plugins:
  - import
rules:
  import/exports-last: error # recommended off
  import/extensions: # recommended off
    - error
    - ignorePackages # https://nodejs.org/api/esm.html#esm_mandatory_file_extensions
    - # TS2691
      pattern:
        ts: never
        tsx: never
  import/first: error # recommended off
  import/newline-after-import: error # recommended off
  import/no-absolute-path: error # recommended off
  import/no-amd: error # recommended off
  import/no-commonjs: error # recommended off
  import/no-cycle: error # recommended off
  import/no-default-export: error # recommended off
  import/no-deprecated: error # recommended off
  import/no-duplicates: error # recommended warn
  import/no-extraneous-dependencies: error # recommended off
  import/no-mutable-exports: error # recommended off
  import/no-named-as-default: error # recommended warn
  import/no-named-as-default-member: error # recommended warn
  import/no-named-default: error # recommended off
  import/no-relative-parent-imports: error # recommended off
  import/no-self-import: error # recommended off
  import/no-unused-modules: error # recommended off
  import/no-useless-path-segments: # recommended off
    - error
    -
      noUselessIndex: true
  import/no-webpack-loader-syntax: error # recommended off
  import/order: # recommended off
    - error
    -
      alphabetize:
        order: asc
      groups:
        - builtin
        - external
        - internal
        -
          - parent
          - sibling
          - index
      newlines-between: always
