extends:
  - plugin:import/recommended
  - plugin:import/react
  - plugin:import/typescript
plugins:
  - import
rules:
  import/exports-last: error # recommended off
  import/extensions: # recommended off
    - error
    - ignorePackages
  import/first: error # recommended off
  import/newline-after-import: error # recommended off
  import/no-absolute-path: error # recommended off
  import/no-amd: error # recommended off
  import/no-commonjs: error # recommended off
  import/no-cycle: error # recommended off
  import/no-default-export: error # recommended off
  import/no-deprecated: error # recommended off
  import/no-extraneous-dependencies: error # recommended off
  import/no-mutable-exports: error # recommended off
  import/no-named-default: error # recommended off
  import/no-relative-parent-imports: error # recommended off
  import/no-self-import: error # recommended off
  import/no-unused-modules: error # recommended off
  import/no-useless-path-segments: # recommended off
    - error
    -
      noUselessIndex: true
  import/no-webpack-loader-syntax: error # recommended off
  import/order: # recommended off
    - error
    -
      alphabetize:
        order: asc
      newlines-between: always
