extends:
  - plugin:node/recommended
plugins:
  - node
rules:
  node/exports-style: error # recommended off
  node/file-extension-in-import: error # recommended off
  node/no-missing-import: # recommended error
    - error
    - tryExtensions: [".js", ".jsx", ".json", ".node", ".ts", ".tsx"] # default does not include TypeScript or JSX
  node/no-unsupported-features/es-syntax:
    - error
    -
      ignores:
        - modules # no-modules https://nodejs.org/api/esm.html, modules transpiled
  node/prefer-global/buffer: error # recommended off
  node/prefer-global/console: error # recommended off
  node/prefer-global/process: error # recommended off
  node/prefer-global/text-decoder: error # recommended off
  node/prefer-global/text-encoder: error # recommended off
  node/prefer-global/url-search-params: error # recommended off
  node/prefer-global/url: error # recommended off
  node/prefer-promises/dns: error # recommended off
  node/prefer-promises/fs: error # recommended off
