extends:
  - plugin:unicorn/recommended
plugins:
  - unicorn
rules:
  unicorn/custom-error-definition: error # recommended off
  unicorn/filename-case: # recommended error kebabCase, allow pascalCase for jsx
    - error
    -
      cases:
        kebabCase: true
        pascalCase: true
  unicorn/no-fn-reference-in-iterator: error # recommended off
  unicorn/no-unsafe-regex: error # recommended off
  unicorn/prefer-replace-all: error # recommended off
