extends:
  - "@package/eslint-config"
overrides:
  - files:
      - "src/index.{[cm]js,[jt]s?(x)}"
    rules:
      import/no-unused-modules: off # whitelist entry point
parserOptions:
  project: "./tsconfig.eslint.json"
settings:
  import/internal-regex: ^@(application|component|library|service)
