enableTelemetry: false

nodeLinker: "${NODE_LINKER:-node-modules}"

packageExtensions:
  "@material-icons/svg@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@vanilla-extract/webpack-plugin@*":
    peerDependencies:
      "@vanilla-extract/css": "*"
  "eslint-module-utils@*":
    peerDependenciesMeta:
      "@typescript-eslint/parser":
        optional: true
      "eslint-import-resolver-node":
        optional: true
  "eslint-plugin-import@*":
    peerDependenciesMeta:
      "@typescript-eslint/parser":
        optional: true
  "eslint-plugin-jest@*":
    peerDependenciesMeta:
      jest:
        optional: true
  "eslint-plugin-monorepo@*":
    dependencies:
      "eslint-import-resolver-node": "^0.3.6"
  "msw@*":
    dependencies:
      debug: "^4.3.2"
  "tsutils-etc@*":
    peerDependenciesMeta:
      typescript:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
