enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@material-icons/svg@*":
    peerDependenciesMeta:
      react:
        optional: true
  eslint-module-utils@*:
    peerDependenciesMeta:
      "@typescript-eslint/parser":
        optional: true
      eslint-import-resolver-node:
        optional: true
  eslint-plugin-import@*:
    peerDependenciesMeta:
      "@typescript-eslint/parser":
        optional: true
  eslint-plugin-monorepo@*:
    dependencies:
      eslint-import-resolver-node: ^0.3.6
  msw@*:
    dependencies:
      debug: ^4.3.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-scaffolder.cjs
    spec: plugins/scaffolder/bundles/@yarnpkg/plugin-scaffolder.js
  - path: .yarn/plugins/@yarnpkg/plugin-typescript-project-references.cjs
    spec: plugins/typescript-project-references/bundles/@yarnpkg/plugin-typescript-project-references.js

yarnPath: .yarn/releases/yarn-3.1.0.cjs
