changesetIgnorePatterns:
  - "**/*.{md,sh}"
  - "**/.*ignore"
  - "**/.{auditci,commitlint,cz,libyear}rc.{json,yaml,yml}"
  - "*.code-workspace"
  - ".{editorconfig,gitattributes,nvmrc}"
  - "{.github,.husky,.yarn,ci,docs}/**/*"
  - constraints.pro

enableGlobalCache: false

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@material-icons/svg@*":
    peerDependenciesMeta:
      react:
        optional: true
  eslint-plugin-monorepo@*:
    dependencies:
      eslint-import-resolver-node: ^0.3.6
  msw@*:
    dependencies:
      debug: ^4.3.4

plugins:
  - checksum: fd0b6bc155a7f5848f1f39a7d49f5303a024532e10060e194eaea8ca37f8c1be21a5126763c8a26404aa7f13ff10038530f44ea5c55db964bf942510da057579
    path: .yarn/plugins/@yarnpkg/plugin-scaffolder.cjs
    spec: plugins/scaffolder/bundles/@yarnpkg/plugin-scaffolder.js
  - checksum: 193dda03386c8a2215e0cc7fc5eb988fd27502bee6d8329005121bd6548c7f576082a71cc37faa4e9f92ef19a4c04a55da6a6d936ffdb4630dde75a430daaebc
    path: .yarn/plugins/@yarnpkg/plugin-typescript-project-references.cjs
    spec: plugins/typescript-project-references/bundles/@yarnpkg/plugin-typescript-project-references.js

yarnPath: .yarn/releases/yarn-4.7.0.cjs
