changesetIgnorePatterns:
  - "**/*.{md,sh}"
  - "**/.*ignore"
  - "**/.{auditci,commitlint,cz,libyear}rc.{json,yaml,yml}"
  - "*.code-workspace"
  - ".{editorconfig,gitattributes,nvmrc}"
  - "{.github,.husky,.yarn,ci,docs}/**/*"
  - constraints.pro

enableGlobalCache: false

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@material-icons/svg@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@tanstack/eslint-plugin-query@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  eslint-plugin-monorepo@*:
    dependencies:
      eslint-import-resolver-node: ^0.3.6

plugins:
  - checksum: 49d1c8f6759ed432704dd4f84c8409497b3597ed5c126b33f40381865682821d820623a077edcdc64507a07c87af40d71d13e9eb3b42e09d22e078d37854c466
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: plugins/nolyfill/bundles/@yarnpkg/plugin-nolyfill.js
  - checksum: 7e0e5050a3b5253b43b09141038d5517495ea01b23cbb127b3af1d5eac5f790c90302ba9694e76022abe7b618a96371848ba1233f6ad559b03b7d91d343a28f0
    path: .yarn/plugins/@yarnpkg/plugin-scaffolder.cjs
    spec: plugins/scaffolder/bundles/@yarnpkg/plugin-scaffolder.js
  - checksum: 193dda03386c8a2215e0cc7fc5eb988fd27502bee6d8329005121bd6548c7f576082a71cc37faa4e9f92ef19a4c04a55da6a6d936ffdb4630dde75a430daaebc
    path: .yarn/plugins/@yarnpkg/plugin-typescript-project-references.cjs
    spec: plugins/typescript-project-references/bundles/@yarnpkg/plugin-typescript-project-references.js

yarnPath: .yarn/releases/yarn-4.10.3.cjs
