changesetIgnorePatterns:
  - "**/*.{md,sh}"
  - "**/.*ignore"
  - "**/.{auditci,commitlint,cz,libyear}rc.{json,yaml,yml}"
  - "*.code-workspace"
  - ".{editorconfig,gitattributes,nvmrc}"
  - "{.github,.husky,.yarn,ci,docs}/**/*"
  - constraints.pro

enableGlobalCache: false

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@material-icons/svg@*":
    peerDependenciesMeta:
      react:
        optional: true
  eslint-plugin-monorepo@*:
    dependencies:
      eslint-import-resolver-node: ^0.3.6
  msw@*:
    dependencies:
      debug: ^4.3.4

plugins:
  - checksum: 379b4239e7f8f0faf33333eb8a6dd72b584274fff17af63bee7362c1259b177d3e2fd3270b874b5ef42cc7e03db980fa030a99e9e5cf0e15b1560b4eb816c942
    path: .yarn/plugins/@yarnpkg/plugin-scaffolder.cjs
    spec: plugins/scaffolder/bundles/@yarnpkg/plugin-scaffolder.js
  - checksum: 86b14ad2ee834f35b6f73086e436b0abc4d853221c799accf0eebec18a850e7515695107e21dd16efac9c546122ca4cfa61449c520bdcbb4d139433f3f2618f0
    path: .yarn/plugins/@yarnpkg/plugin-typescript-project-references.cjs
    spec: plugins/typescript-project-references/bundles/@yarnpkg/plugin-typescript-project-references.js

yarnPath: .yarn/releases/yarn-4.2.2.cjs
