extends:
  - "@package/eslint-config"
overrides:
  - files:
      - "src/index.{[cm]js,[jt]s?(x)}"
    rules:
      filenames/no-index: off # whitelist entry point
      import/no-unused-modules: off # whitelist entry point
  - files:
      - "playwright/**/*"
    settings:
      disable/plugins:
        - jest # plugin mistakes playwright tests for jest tests
  - files:
      - "src/**/*"
    rules:
      node/no-unsupported-features/es-syntax: off # src code does not run on node runtime
parserOptions:
  project: "./tsconfig.eslint.json"
rules:
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        Props: true # common abbreviation
        i18n: true # common numeronym
        props: true # common abbreviation
settings:
  import/internal-regex: ^@(application|component|library|service)
