extends:
  - ./a11y.yaml
  - ./array.yaml
  - ./arrow-functions.yaml
  - ./compat.yaml
  - ./cypress.yaml
  - ./eslint.yaml
  - ./eslint-comments.yaml
  - ./disable.yaml
  - ./filenames.yaml
  - ./functional.yaml
  - ./import.yaml
  - ./jest.yaml
  - ./jsdoc.yaml
  - ./monorepo.yaml
  - ./node.yaml
  - ./promise.yaml
  - ./react.yaml
  - ./rxjs.yaml
  - ./secrets.yaml
  - ./security.yaml
  - ./sonar.yaml
  - ./testing-library.yaml
  - ./tsdoc.yaml
  - ./typescript.yaml
  - ./unicorn.yaml
