env:
  cypress/globals: true
extends:
  - plugin:cypress/recommended
plugins:
  - cypress
rules:
  cypress/assertion-before-screenshot: error # recommended off
  cypress/no-force: error # recommended off
  cypress/require-data-selectors: error # recommended off
