env:
  jest/globals: true
extends:
  - plugin:jest/all
plugins:
  - jest
rules:
  jest/no-restricted-matchers:
    - error
    - resolves: "Use `expect(await promise)` instead." # previously jest/no-expect-resolves
      toBeFalsy: "Avoid `toBeFalsy`" # previously jest/no-truthy-falsy
      toBeTruthy: "Avoid `toBeTruthy`" # previously jest/no-truthy-falsy
      toMatchSnapshot: "Use `toMatchInlineSnapshot()` instead" # previously jest/prefer-inline-snapshots
      toThrowErrorMatchingSnapshot: "Use `toThrowErrorMatchingInlineSnapshot()` instead" # previously jest/prefer-inline-snapshots
  jest/prefer-expect-assertions: off # all error, too verbose
