extends:
  - plugin:react/recommended
  - plugin:react-perf/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - react-hooks
  - react-perf
rules:
  react/button-has-type: error # recommended off
  react/destructuring-assignment: error # recommended off
  react/forbid-component-props: error # recommended off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-boolean-value: error # recommended off
  react/jsx-curly-brace-presence: error # recommended off
  react/jsx-filename-extension: # recommended off
    - error
    - extensions:
        - ".tsx"
  react/jsx-fragments: error # recommended off
  react/jsx-handler-names: error # recommended off
  react/jsx-no-bind: error # recommended off
  react/jsx-no-literals: error # recommended off
  react/jsx-no-script-url: error # recommended off
  react/jsx-no-useless-fragment: error # recommended off
  react/jsx-pascal-case: error # recommended off
  react/jsx-sort-default-props: error # recommended off
  react/jsx-sort-props: error # recommended off
  react/no-access-state-in-setstate: error # recommended off
  react/no-array-index-key: error # recommended off
  react/no-danger: error # recommended off
  react/no-did-mount-set-state: error # recommended off
  react/no-did-update-set-state: error # recommended off
  react/no-multi-comp: error # recommended off
  react/no-redundant-should-component-update: error # recommended off
  react/no-this-in-sfc: error # recommended off
  react/no-typos: error # recommended off
  react/no-unsafe: error # recommended off
  react/no-unused-state: error # recommended off
  react/no-will-update-set-state: error # recommended off
  react/prefer-es6-class: error # recommended off
  react/prefer-stateless-function: error # recommended off
  react/prop-types: off # recommended error, unnecessary w/ typescript
  react/require-optimization: error # recommended off
  react/self-closing-comp: error # recommended off
  react/sort-comp: # recommended off
    - error
    - order:
        - static-variables
        - static-methods
        - defaultProps # included in lifecycle, but conflicts with @typescript-eslint/member-ordering
        - instance-variables
        - lifecycle
        - render
        - everything-else
  react/state-in-constructor: error # recommended off
  react/static-property-placement: error # recommended off
  react/style-prop-object: error # recommended off
  react/void-dom-elements-no-children: error # recommended off
  react-hooks/exhaustive-deps: error
  react-hooks/rules-of-hooks: error
settings:
  react:
    version: detect
