extends:
  - plugin:rxjs/recommended
plugins:
  - rxjs
rules:
  rxjs/no-compat: error # recommended off
  rxjs/no-ignored-error: error # recommended off
  rxjs/no-ignored-observable: error # recommended off
  rxjs/no-subclass: error # recommended off
  rxjs/throw-error: error # recommended off
