extends:
  - plugin:jest-dom/recommended
  - plugin:testing-library/recommended
  - plugin:testing-library/react
plugins:
  - jest-dom
  - testing-library
rules:
  testing-library/no-await-sync-events: error # recommended off
  testing-library/no-manual-cleanup: error # recommended off
  testing-library/no-render-in-setup: # recommended off
    - error
    - allowTestingFrameworkSetupHook: beforeAll
  testing-library/no-wait-for-empty-callback: error # recommended off
  testing-library/no-wait-for-snapshot: error # recommended off
  testing-library/prefer-explicit-assert: error # recommended off
  testing-library/prefer-presence-queries: error # recommended off
  testing-library/prefer-wait-for: error # recommended off
