extends:
  - plugin:jest-dom/recommended
  - plugin:testing-library/recommended
  - plugin:testing-library/react
plugins:
  - jest-dom
  - testing-library
rules:
  testing-library/no-get-by-for-checking-element-not-present: error # recommended off
  testing-library/no-manual-cleanup: error # recommended off
  testing-library/prefer-explicit-assert: error # recommended off
