extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
overrides:
  - files:
      - "**/*.ts?(x)"
    parser: "@typescript-eslint/parser"
  - files:
      - "**/*.spec.[jt]s?(x)"
      - "**/*.test.[jt]s?(x)"
    rules:
      "@typescript-eslint/no-magic-numbers": off # not a concern for tests
      "@typescript-eslint/no-unused-expressions": off # necessary for jest expectations
      "@typescript-eslint/unbound-method": off # necessary for jest expectations
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/array-type": # recommended off
    - error
    - default: array-simple
  "@typescript-eslint/ban-ts-comment": error # recommended off
  "@typescript-eslint/class-literal-property-style": error # recommended off
  "@typescript-eslint/consistent-type-definitions": error # recommended off
  "@typescript-eslint/dot-notation": error # recommended off
  "@typescript-eslint/explicit-function-return-type": error # recommended warn
  "@typescript-eslint/explicit-member-accessibility": error # recommended off
  "@typescript-eslint/explicit-module-boundary-types": error # recommended off
  "@typescript-eslint/generic-type-naming": error # recommended off
  "@typescript-eslint/init-declarations": error # recommended off
  "@typescript-eslint/member-ordering": error # recommended off
  "@typescript-eslint/method-signature-style": error # recommended off
  "@typescript-eslint/naming-convention": # recommended off
    - error
    - # default
      selector: default
      format:
        - camelCase
      leadingUnderscore: allow
      trailingUnderscore: allow
    - # default
      selector: variable
      format:
        - camelCase
        - UPPER_CASE
        - PascalCase # https://airbnb.io/javascript/react/#naming
      leadingUnderscore: allow
      trailingUnderscore: allow
    - # default
      selector: typeLike
      format:
        - PascalCase
    - # https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#enum
      selector: enumMember
      format:
        - PascalCase
  "@typescript-eslint/no-base-to-string": error # recommended off
  "@typescript-eslint/no-dynamic-delete": error # recommended off
  "@typescript-eslint/no-explicit-any": error # recommended warn
  "@typescript-eslint/no-extra-non-null-assertion": error # recommended off
  "@typescript-eslint/no-extra-semi": error # recommended off
  "@typescript-eslint/no-extraneous-class": error # recommended off
  "@typescript-eslint/no-floating-promises": error # recommended off
  "@typescript-eslint/no-implied-eval": error # recommended off
  "@typescript-eslint/no-invalid-this": error # recommended off
  "@typescript-eslint/no-invalid-void-type": error # recommended off
  "@typescript-eslint/no-magic-numbers": error # recommended off
  "@typescript-eslint/no-non-null-asserted-optional-chain": error # recommended off
  "@typescript-eslint/no-parameter-properties": error # recommended off
  "@typescript-eslint/no-require-imports": error # recommended off
  "@typescript-eslint/no-throw-literal": error # recommended off
  "@typescript-eslint/no-type-alias": error # recommended off
  "@typescript-eslint/no-unnecessary-boolean-literal-compare": error # recommended off
  "@typescript-eslint/no-unnecessary-condition": # recommended off
    - error
    - checkArrayPredicates: true # default false, avoid breaking change
  "@typescript-eslint/no-unnecessary-qualifier": error # recommended off
  "@typescript-eslint/no-unnecessary-type-arguments": error # recommended off
  "@typescript-eslint/no-unsafe-assignment": error # recommended off
  "@typescript-eslint/no-unsafe-call": error # recommended off
  "@typescript-eslint/no-unsafe-member-access": error # recommended off
  "@typescript-eslint/no-unsafe-return": error # recommended off
  "@typescript-eslint/no-unused-expressions": error # recommended off
  "@typescript-eslint/no-unused-vars-experimental": error # recommended off
  "@typescript-eslint/no-useless-constructor": error # recommended off
  "@typescript-eslint/prefer-as-const": error # recommended off
  "@typescript-eslint/prefer-for-of": error # recommended off
  "@typescript-eslint/prefer-function-type": error # recommended off
  "@typescript-eslint/prefer-nullish-coalescing": error # recommended off
  "@typescript-eslint/prefer-optional-chain": error # recommended off
  "@typescript-eslint/prefer-readonly": error # recommended off
  "@typescript-eslint/prefer-readonly-parameter-types": error # recommended off
  "@typescript-eslint/prefer-reduce-type-parameter": error # recommended off
  "@typescript-eslint/prefer-ts-expect-error": error # recommended off
  "@typescript-eslint/promise-function-async": error # recommended off
  "@typescript-eslint/require-array-sort-compare": error # recommended off
  "@typescript-eslint/restrict-plus-operands": error # recommended off
  "@typescript-eslint/restrict-template-expressions": error # recommended off
  "@typescript-eslint/return-await": error # recommended off
  "@typescript-eslint/switch-exhaustiveness-check": error # recommended off
  "@typescript-eslint/unified-signatures": error # recommended off
