export default [
  import("./a11y.mjs"),
  import("./array.mjs"),
  // import("./arrow-functions.mjs"),
  import("./compat.mjs"),
  import("./deprecation.mjs"),
  import("./eslint.mjs"),
  // import("./eslint-comments.mjs"),
  // import("./disable.mjs"),
  // import("./filenames.mjs"),
  import("./functional.mjs"),
  // import("./import.mjs"),
  import("./jest.mjs"),
  import("./jsdoc.mjs"),
  // import("./monorepo.mjs"),
  // import("./node.mjs"),
  import("./playwright.mjs"),
  import("./promise.mjs"),
  import("./query.mjs"),
  // import("./react.mjs"),
  import("./regex.mjs"),
  // import("./rxjs.mjs"),
  import("./secrets.mjs"),
  import("./security.mjs"),
  import("./sonar.mjs"),
  // import("./testing-library.mjs"),
  // import("./tsdoc.mjs"),
  import("./typescript.mjs"),
  import("./unicorn.mjs"),
];
