extends:
  - plugin:node/recommended
plugins:
  - node
rules:
  node/exports-style: error # recommended off
  node/file-extension-in-import:
    - error # recommended off
    - always # https://nodejs.org/api/esm.html#esm_mandatory_file_extensions
    - ".js": never # typescript cannot find type definitions
      ".jsx": never # typescript cannot find type definitions
      ".ts": never # TS2691
      ".tsx": never # TS2691
  node/global-require: error # recommended off
  node/no-missing-import:
    - error # recommended error
    - tryExtensions: # default does not include TypeScript or JSX
        - ".js"
        - ".jsx"
        - ".json"
        - ".mjs"
        - ".node"
        - ".ts"
        - ".tsx"
  node/no-mixed-requires: error # recommended off
  node/no-new-require: error # recommended off
  node/no-path-concat: error # recommended off
  node/no-process-env: error # recommended off
  node/no-process-exit: error # recommended off
  node/no-sync: error # recommended off
  node/no-unsupported-features/es-syntax:
    - error # recommended error
    - ignores:
        - modules # no-modules https://nodejs.org/api/esm.html, modules transpiled
  node/prefer-global/buffer: error # recommended off
  node/prefer-global/console: error # recommended off
  node/prefer-global/process: error # recommended off
  node/prefer-global/text-decoder: error # recommended off
  node/prefer-global/text-encoder: error # recommended off
  node/prefer-global/url-search-params: error # recommended off
  node/prefer-global/url: error # recommended off
  node/prefer-promises/dns: error # recommended off
  node/prefer-promises/fs: error # recommended off
