extends:
  - plugin:promise/recommended
plugins:
  - promise
rules:
  promise/no-nesting: error # recommended warn
  promise/no-promise-in-callback: error # recommended warn
  promise/no-callback-in-promise: error # recommended warn
  promise/no-multiple-resolved: error # recommended off
  promise/no-return-in-finally: error # recommended warn
  promise/spec-only: error # recommended off
  promise/valid-params: error # recommended warn
