extends:
  - plugin:jest-dom/recommended
  - plugin:testing-library/dom
  - plugin:testing-library/react
plugins:
  - jest-dom
  - testing-library
rules:
  testing-library/no-debugging-utils: error # react warn
  testing-library/prefer-explicit-assert: error # dom off
  testing-library/prefer-user-event: error # dom off
