extends:
  - plugin:jest-dom/recommended
  - plugin:testing-library/dom
  - plugin:testing-library/react
plugins:
  - jest-dom
  - testing-library
rules:
  testing-library/no-await-sync-events: error # dom off
  testing-library/no-global-regex-flag-in-query: error # dom off
  testing-library/no-manual-cleanup: error # dom off
  testing-library/prefer-explicit-assert: error # dom off
  testing-library/prefer-user-event: error # dom off
  testing-library/prefer-wait-for: error # dom off
