#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# yarn constraints --fix # TODO: if `constraints.pro` is modified
# yarn install # TODO: if `package.json` is modified
# yarn dedupe # TODO: if `yarn.lock` is modified
yarn workspaces foreach --since="${GIT_DEFAULT_BRANCH}" --verbose run precommit
