extends:
  - "@package/eslint-config"
overrides:
  - files:
      - "src/index.[jt]s?(x)"
    rules:
      filenames/no-index: off # whitelist entry point
  - files:
      - "**/*.spec.[jt]s?(x)"
      - "**/*.test.[jt]s?(x)"
    rules:
      max-lines-per-function: off # jest tests and suites are functions
      max-statements: off # jest tests and suites are functions
  - files:
      - "cypress/**/*"
    rules:
      "@typescript-eslint/no-unsafe-call": off # expect takes `any`
      "@typescript-eslint/no-unsafe-member-access": off # expect takes `any`
      filenames/no-index: off
    settings:
      disable/plugins:
        - jest
parserOptions:
  project: "./tsconfig.eslint.json"
settings:
  import/internal-regex: ^@(application|component|package|service)
