extends:
  - "@package/eslint-config"
overrides:
  - files:
      - "src/index.{[cm]js,[jt]s?(x)}"
    rules:
      filenames/no-index: off # whitelist entry point
      import/no-unused-modules: off # whitelist entry point
  - files:
      - "cypress/**/*"
    rules:
      "@typescript-eslint/no-unsafe-call": off # expect takes `any`
      "@typescript-eslint/no-unsafe-member-access": off # expect takes `any`
      filenames/no-index: off # required by cypress
      import/no-unused-modules: off # cypress files are not es modules
    settings:
      disable/plugins:
        - jest # plugin mistakes cypress' use of mocha (framework) and chai (expectations) as jest (jasmine)
        - promise # plugin confuses cypress' `.then()` functions with promises
parserOptions:
  project: "./tsconfig.eslint.json"
rules:
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        i18n: true # common numeronym
settings:
  import/internal-regex: ^@(application|component|library|service)
