extends:
  - "@package/eslint-config"
overrides:
  - files:
      - "src/index.{[cm]js,[jt]s?(x)}"
    rules:
      filenames/no-index: off # whitelist entry point
      import/no-unused-modules: off # whitelist entry point
  - files:
      - "cypress/**/*"
    rules:
      "@typescript-eslint/no-unsafe-call": off # expect takes `any`
      "@typescript-eslint/no-unsafe-member-access": off # expect takes `any`
      filenames/no-index: off # required by cypress
      import/no-unused-modules: off # cypress files are not es modules
    settings:
      disable/plugins:
        - jest # plugin mistakes cypress' use of mocha (framework) and chai (expectations) as jest (jasmine)
        - promise # plugin confuses cypress' `.then()` functions with promises
  - files:
      - "src/**/*"
    rules:
      node/no-unsupported-features/es-syntax: off # src code does not run on node runtime
  - files:
      - "src/**/*.css.{[cm]js,[jt]s?(x)}"
    rules:
      "@typescript-eslint/naming-convention":
        - error
        - # default
          selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow
        - # default
          selector: variable
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase # https://airbnb.io/javascript/react/#naming
          leadingUnderscore: allow
          trailingUnderscore: allow
        - # default
          selector: typeLike
          format:
            - PascalCase
        - # https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#enum
          selector: enumMember
          format:
            - PascalCase
        - # previously @typescript-eslint/generic-type-naming
          selector: typeParameter
          format:
            - PascalCase
          prefix:
            - T
        - # allow css at-rules, pseudo-classes, pseudo-elements, selectors, and properties as object keys
          selector: objectLiteralProperty
          format: null
parserOptions:
  project: "./tsconfig.eslint.json"
rules:
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        Props: true # common abbreviation
        i18n: true # common numeronym
        props: true # common abbreviation
settings:
  import/internal-regex: ^@(application|component|library|service)
