extends:
  - "@package/eslint-config"
overrides:
  -
    files:
      - "src/index.tsx"
    rules:
      filenames/no-index: off
  -
    files:
      - "*/**"
    rules:
      import/order: off # false positives on eslint-plugin-import@2.19.1, fixed on master
parserOptions:
  project:
    - "./tsconfig.json"
settings:
  import/internal-regex: ^@(application|component|package|service)
