extends:
  - "@package/eslint-config"
overrides:
  - files:
      - "src/index.[jt]s?(x)"
    rules:
      filenames/no-index: off # whitelist entry point
  - files:
      - "**/*.spec.[jt]s?(x)"
      - "**/*.test.[jt]s?(x)"
    rules:
      max-lines-per-function: off # jest tests and suites are functions
      max-statements: off # jest tests and suites are functions
parserOptions:
  project: "./tsconfig.eslint.json"
settings:
  import/internal-regex: ^@(application|component|package|service)
