extends:
  - "@package/eslint-config"
overrides:
  -
    files:
      - "src/index.tsx"
    rules:
      filenames/no-index: off # whitelist react entry point
  -
    files:
      - "**/*.test.ts?(x)"
    rules:
      max-lines-per-function: off # jest tests and suites are functions
      max-statements: off # jest tests and suites are functions
parserOptions:
  project: "./tsconfig.json"
settings:
  import/internal-regex: ^@(application|component|package|service)
