extends:
  - "@package/eslint-config"
parserOptions:
  extraFileExtensions:
    - ".json"
    - ".md"
  project:
    - "./tsconfig.json"
settings:
  import/internal-regex: ^@(application|component|package|service)
