name: branch
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test on node ${{matrix.node}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 13
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      # awaiting https://github.com/actions/checkout/pull/155
      - run: git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --depth=1 origin ${{github.context.pull_request.base.sha}}
      - run: yarn install --frozen-lockfile
      - run: yarn compile --since="${{github.event.pull_request.base.sha}}"
      - run: yarn test:ci:branch --since="${{github.event.pull_request.base.sha}}"
      - run: yarn lint:diff --since="${{github.event.pull_request.base.sha}}"
