name: branch
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test on node ${{matrix.node}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
        os:
#          - macos-latest
          - ubuntu-latest
#          - windows-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{matrix.node}}
      # awaiting https://github.com/actions/checkout/pull/155
      - run: git -c protocol.version=2 fetch --depth=1 --no-recurse-submodules --no-tags --progress --prune origin ${{github.event.pull_request.base.ref}}:${{github.event.pull_request.base.ref}}
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.0
        id: yarn-cache
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: ${{matrix.os}}-${{matrix.node}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{matrix.os}}-${{matrix.node}}-yarn-
      - run: yarn install --frozen-lockfile --offline
        if: steps.yarn-cache.outputs.cache-hit == 'true'
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn compile --since="${{github.event.pull_request.base.ref}}"
      - run: yarn test:ci:branch --since="${{github.event.pull_request.base.ref}}"
      - run: yarn lint:diff --since="${{github.event.pull_request.base.ref}}"
      - run: yarn fmt:diff:check --since="${{github.event.pull_request.base.ref}}"
      - run: yarn build --since="${{github.event.pull_request.base.ref}}"
      - run: yarn bundlesize --since="${{github.event.pull_request.base.ref}}"
      - run: yarn cy:run --since="${{github.event.pull_request.base.ref}}"
