name: dependabot
on:
  push:
    branches: [dependabot/npm_and_yarn/**]
jobs:
  bulid:
    if: github.actor == "dependabot[bot]"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          #lfs: true
          persist-credentials: false
      - run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-hashes
      - uses: actions/cache@v2.1.3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{runner.os}}-lfs-${{hashFiles('.lfs-hashes')}}
          restore-keys: |
            ${{runner.os}}-lfs-
      - run: git lfs pull
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Autofix Lockfile
        run: |
          yarn install
          yarn dedupe
        env:
          YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts
      - name: Configure Git
        run: |
          # use personal access token to allow triggering new workflow
          BASIC_AUTH=$(echo -n "x-access-token:${{secrets.GH_TOKEN}}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name '${{github.event.commits[0].author.name}}'
          git config --global user.email '${{github.event.commits[0].author.email}}'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"
      - name: Commit Changes
        run: |
          git add yarn.lock # add .yarn/cache .pnp.* if using zero-installs
          git commit -m "chore(deps): dependabot autofix"
          git push
    timeout-minutes: 15
