name: pull-request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test on node ${{matrix.node}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node:
          - 12
          - 14
          - 16
          - 17
        os:
          #- macos-latest
          - ubuntu-latest
          #- windows-latest
    env:
      NODE_LINKER: pnp
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          # awaiting https://github.com/facebook/jest/issues/11271
          fetch-depth: 0
          #lfs: true
          # awaiting https://github.com/actions/checkout/issues/317
          ref: ${{github.event.pull_request.head.ref}}
      - run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-hashes
      - uses: actions/cache@v2.1.6
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{matrix.os}}-lfs-${{hashFiles('.lfs-hashes')}}
          restore-keys: |
            ${{matrix.os}}-lfs-
      - run: git lfs pull
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{matrix.node}}
      # awaiting https://github.com/actions/checkout/pull/155
      - run: git -c protocol.version=2 fetch --no-recurse-submodules --no-tags --progress --prune origin ${{github.event.pull_request.base.ref}}:${{github.event.pull_request.base.ref}}
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: |
            ${{steps.yarn-cache-dir-path.outputs.dir}}
            .yarn/install-state.gz
            .yarn/unplugged
          key: ${{matrix.os}}-${{matrix.node}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{matrix.os}}-${{matrix.node}}-yarn-
      - run: yarn install --immutable
        env:
          CYPRESS_INSTALL_BINARY: 0
      - run: yarn constraints
      - uses: actions/cache@v2.1.6
        id: typescript-cache
        with:
          path: "**/build"
          key: ${{matrix.os}}-${{matrix.node}}-typescript-${{github.sha}}
          restore-keys: |
            ${{matrix.os}}-${{matrix.node}}-typescript-
      - run: yarn compile --since="${{github.event.pull_request.base.ref}}"
      - uses: actions/cache@v2.1.6
        id: jest-cache
        with:
          path: "**/cache/jest"
          key: ${{matrix.os}}-${{matrix.node}}-jest-${{github.sha}}
          restore-keys: |
            ${{matrix.os}}-${{matrix.node}}-jest-
      - run: yarn test:ci:branch --since="${{github.event.pull_request.base.ref}}"
      - uses: actions/cache@v2.1.6
        id: eslint-cache
        with:
          path: "**/.eslintcache"
          key: ${{matrix.os}}-${{matrix.node}}-eslint-${{github.sha}}
          restore-keys: |
            ${{matrix.os}}-${{matrix.node}}-eslint-
      - run: yarn lint:diff --since="${{github.event.pull_request.base.ref}}"
      - run: yarn format:diff:check --since="${{github.event.pull_request.base.ref}}"
      - uses: actions/cache@v2.1.6
        id: webpack-cache
        with:
          path: "**/.yarn/.cache/webpack"
          key: ${{matrix.os}}-${{matrix.node}}-webpack-${{github.sha}}
          restore-keys: |
            ${{matrix.os}}-${{matrix.node}}-webpack-
      - run: yarn build --since="${{github.event.pull_request.base.ref}}"
      - run: yarn bundlesize --since="${{github.event.pull_request.base.ref}}"
      - run: |
          yarn cy:install --since="${{github.event.pull_request.base.ref}}"
          yarn cy:ci --since="${{github.event.pull_request.base.ref}}"
      - run: yarn commitlint --from="${{github.event.pull_request.base.ref}}"
    timeout-minutes: 15
